databases:
  - name: deploy-trial
    databaseName: deploy-trial
    user: deploy-trial

services:
  - type: web
    name: deploy-trial
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: deploy-trial
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false